In [4]:
import numpy as np 
from scipy import stats

# File input/output: scipy.io

In [5]:
from scipy import io as spio
a = np.ones((3, 3))
spio.savemat('file.mat', {"a":a})
data = spio.loadmat('file.mat', struct_as_record=True)
data['a']

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Special Functions


## Linear Algebra Operations: scipy.linalg

In [6]:
from scipy import linalg

In [7]:
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

#### Determinant

In [8]:
linalg.det(arr)

-2.0

In [9]:
m = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 100]])
print(m.shape)
print(linalg.det(m))

(3, 3)
-362.99999999999994


In [10]:
#If we do not pass square matrix 
mat = np.array([[2, 3, 4], [3, 4, 5]])
linalg.det(mat)

ValueError: Last 2 dimensions of the array must be square but received shape (2, 3).

#### Inverse Functions

In [ ]:
iarr = linalg.inv(arr)
iarr

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
m

array([[ 11,  22,  33],
       [ 44,  55,  66],
       [ 77,  88, 100]])

In [ ]:
linalg.inv(m)

array([[ 0.84848485, -1.93939394,  1.        ],
       [-1.87878788,  3.96969697, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

In [ ]:
a1 = np.array([[3, 2], [6, 4]]) #Singular Metrix
linalg.inv(a1) #Does not exist 

LinAlgError: singular matrix

In [ ]:
a2 = np.arange(9).reshape((3, 3)) + np.diag([1, 0, 1])
ua2, spec, vha2 = linalg.svd(a2)

In [ ]:
spec

array([14.88982544,  0.45294236,  0.29654967])

In [ ]:
sa2 = np.diag(spec)
svd_mat = ua2.dot(sa2).dot(vha2)
np.allclose(svd_mat, a2)

True

In [ ]:
time_step = 0.02
period = 5.
time_vec = np.arange(0, 20, time_step)
sig = np.sin(2*np.pi/period*time_vec) + 0.5*np.random.randn(time_vec.size)

In [ ]:
from scipy import fftpack
sample_freq = fftpack.fftfreq(sig.size, d=time_step)
sig_fft = fftpack.fft(sig)

pidxs = np.where(sample_freq > 0)
freqs = sample_freq[pidxs]
power = np.abs(sig_fft)[pidxs]

In [ ]:
from scipy import fftpack